/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enrollmentsystem;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gebruiker
 */
public class TeachersForm extends javax.swing.JFrame {

    /**
     * Creates new form TeachersForm
     */
    String filterstring = ";";
    String teacherid;
    teachers teach = new teachers();
    public TeachersForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teachadd = new javax.swing.JTextField();
        teachnum = new javax.swing.JTextField();
        teachsts = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        teachid = new javax.swing.JTextField();
        teachname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        teachdept = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        op1 = new javax.swing.JComboBox();
        tidfil = new javax.swing.JTextField();
        op2 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tnfil1 = new javax.swing.JTextField();
        tnfil2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tdfil = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tafil1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tafil2 = new javax.swing.JTextField();
        op3 = new javax.swing.JComboBox();
        op4 = new javax.swing.JComboBox();
        op5 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        tcnfil = new javax.swing.JTextField();
        op6 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        tsfil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter Teacher ID:");

        jLabel2.setText("Enter Teacher Name:");

        jLabel3.setText("Enter Teacher Department:");

        jLabel4.setText("Enter Teacher Address:");

        jLabel5.setText("Enter Teacher Contact#:");

        jLabel6.setText("Enter Teacher Status:");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Teacher ID", "Name", "Department", "Address", "Cont. Num.", "Status"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable3);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Filter"));

        jLabel7.setText("Teacher ID");

        op1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", ">", "<", ">=", "<=", "<>" }));
        op1.setToolTipText("");
        op1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op1ActionPerformed(evt);
            }
        });

        tidfil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tidfilKeyReleased(evt);
            }
        });

        op2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OR", "AND" }));
        op2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Teacher Name");

        jLabel9.setText("Starts");

        jLabel10.setText("Ends");

        tnfil1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tnfil1KeyReleased(evt);
            }
        });

        tnfil2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tnfil2KeyReleased(evt);
            }
        });

        jLabel11.setText("Teacher Department");

        tdfil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tdfilKeyReleased(evt);
            }
        });

        jLabel12.setText("Teacher Address");

        jLabel13.setText("Starts");

        tafil1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tafil1KeyReleased(evt);
            }
        });

        jLabel14.setText("Ends");

        tafil2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tafil2KeyReleased(evt);
            }
        });

        op3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OR", "AND" }));
        op3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op3ActionPerformed(evt);
            }
        });

        op4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OR", "AND" }));
        op4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op4ActionPerformed(evt);
            }
        });

        op5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OR", "AND" }));
        op5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op5ActionPerformed(evt);
            }
        });

        jLabel15.setText("Teacher Contact Number");

        tcnfil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tcnfilKeyReleased(evt);
            }
        });

        op6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OR", "AND" }));
        op6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op6ActionPerformed(evt);
            }
        });

        jLabel16.setText("Teacher Status");

        tsfil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tsfilKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tcnfil)
                    .addComponent(tsfil)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(op2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(op1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel8))
                                    .addGap(10, 10, 10)
                                    .addComponent(tidfil, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tnfil1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tnfil2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel11)
                                .addComponent(tdfil))
                            .addComponent(jLabel12)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tafil1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tafil2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(op3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(op4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(op5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(op6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(op1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tidfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(op2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(tnfil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(tnfil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(op3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tdfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(op4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(tafil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(tafil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(op5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tcnfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(op6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tsfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teachadd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teachnum, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teachdept, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teachname, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teachid, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teachsts, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(teachid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(teachdept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(teachadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(teachnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(teachsts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ShowTeachRec(){
        DefaultTableModel tblmodel = (DefaultTableModel) jTable3.getModel();
        tblmodel.setRowCount(0);

        if(!tidfil.getText().equals("")){
            filterstring = " where teachid " + op1.getSelectedItem() + tidfil.getText();
        }
        if(!tnfil1.getText().equals("")){
            if(tidfil.getText().equals("")){
                filterstring = " where teachname like '"+tnfil1.getText()+"%'";
            }else if(!tnfil2.getText().equals("")){
                filterstring += " "+op2.getSelectedItem()+" teachname like '"+tnfil1.getText()+"%'";
            }else{
                filterstring += " "+op2.getSelectedItem()+" teachname like '"+tnfil1.getText()+"%'";
            }
        }
        if(!tnfil2.getText().equals("")){
            if(tidfil.getText().equals("") && tnfil1.getText().equals("")){
                filterstring = " where teachname like '%"+tnfil2.getText()+"'";
            }else if(tnfil1.getText().equals("")){
                filterstring += " teachname like '%"+tnfil2.getText()+"'";
            }else if(!tnfil1.getText().equals("") && tidfil.getText().equals("")){
                filterstring += " and teachname like '%"+tnfil2.getText()+"'";
            }else{
                filterstring += " and teachname like '%"+tnfil2.getText()+"'";
            }
        }
        if(!tdfil.getText().equals("")){
            if(tidfil.getText().equals("") && tnfil1.getText().equals("") && tnfil2.getText().equals("")){
                filterstring = " where teachdept like '"+tdfil.getText()+"%'";
            }else{
                filterstring += " "+op3.getSelectedItem()+" teachdept like '"+tdfil.getText()+"%'";
            }
        }
        if(!tafil1.getText().equals("")){
            if(tidfil.getText().equals("") && tnfil1.getText().equals("") && tnfil2.getText().equals("") && tdfil.getText().equals("")){
                filterstring = " where teachadd like '"+tafil1.getText()+"%'";
            }else if(!tafil2.getText().equals("")){
                filterstring += " "+op4.getSelectedItem()+" teachadd like '"+tafil1.getText()+"%'";
            }else{
                filterstring += " "+op4.getSelectedItem()+" teachadd like '"+tafil1.getText()+"%'";
            }
        }
        if(!tafil2.getText().equals("")){
            if(tidfil.getText().equals("") && tnfil1.getText().equals("") && tnfil2.getText().equals("") && tdfil.getText().equals("") && tafil1.getText().equals("")){
                filterstring = " where teachadd like '%"+tafil2.getText()+"'";
            }else if(tafil1.getText().equals("")){
                filterstring += " "+op4.getSelectedItem()+" teachadd like '%"+tafil2.getText()+"'";
            }else if(!tafil1.getText().equals("") && tidfil.getText().equals("") && tnfil1.getText().equals("") && tnfil2.getText().equals("") && tdfil.getText().equals("")){
                filterstring += " and teachadd like '%"+tafil2.getText()+"'";
            }else{
                filterstring += " and teachadd like '%"+tafil2.getText()+"'";
            }
        }
        if(!tcnfil.getText().equals("")){
            if(tidfil.getText().equals("") && tnfil1.getText().equals("") && tnfil2.getText().equals("") && tdfil.getText().equals("") && tafil1.getText().equals("") && tafil2.getText().equals("")){
                filterstring = " where teachnum like '"+tcnfil.getText()+"%'";
            }else{
                filterstring += " "+op5.getSelectedItem()+" teachnum like '"+tcnfil.getText()+"%'";
            }
        }
        if(!tsfil.getText().equals("")){
            if(tidfil.getText().equals("") && tnfil1.getText().equals("") && tnfil2.getText().equals("") && tdfil.getText().equals("") && tafil1.getText().equals("") && tafil2.getText().equals("") && tcnfil.getText().equals("")){
                filterstring = " where teachsts like '"+tsfil.getText()+"%'";
            }else{
                filterstring += " "+op6.getSelectedItem()+" teachsts like '"+tsfil.getText()+"%'";
            }
        }
         
        
    
        
        DBConnect c = new DBConnect();
        
        try{
            String query = "select * from teachers" + filterstring;
            c.rs = c.st.executeQuery(query);
                while(c.rs.next()){
                    String id = c.rs.getString("teachid");
                    String name = c.rs.getString("teachname");
                    String department = c.rs.getString("teachdept");
                    String address = c.rs.getString("teachadd");
                    String number = c.rs.getString("teachnum");
                    String status = c.rs.getString("teachsts");
                    String[] item = {id,name,department,address,number,status};
                    tblmodel.addRow(item);
                }
        }catch(Exception ex){
            System.out.println(ex);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        teach.AddTeach(Integer.parseInt(teachid.getText()), teachname.getText(), teachdept.getText(), teachadd.getText(), teachnum.getText(), teachsts.getText());
        ShowTeachRec();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        teach.DelTeach(filterstring);
        ShowTeachRec();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        teach.EditTeach(Integer.parseInt(teachid.getText()), teachname.getText(), teachdept.getText(), teachadd.getText(), teachnum.getText(), teachsts.getText());
        ShowTeachRec();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        String name;
        String dept;
        String addr;
        String num;
        String sts;
        
        int[] selectRow = jTable3.getSelectedRows();
        teacherid = (String) jTable3.getValueAt(selectRow[0], 0);
        teachid.setText(teacherid);
        name = (String) jTable3.getValueAt(selectRow[0], 1);
        teachname.setText(name);
        dept = (String) jTable3.getValueAt(selectRow[0], 2);
        teachdept.setText(dept);
        addr = (String) jTable3.getValueAt(selectRow[0], 3);
        teachadd.setText(addr);
        num = (String) jTable3.getValueAt(selectRow[0], 4);
        teachnum.setText(num);
        sts = (String) jTable3.getValueAt(selectRow[0], 5);
        teachsts.setText(sts);
    }//GEN-LAST:event_jTable3MouseClicked

    private void op1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op1ActionPerformed
        ShowTeachRec();
    }//GEN-LAST:event_op1ActionPerformed

    private void tidfilKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tidfilKeyReleased
        ShowTeachRec();
    }//GEN-LAST:event_tidfilKeyReleased

    private void op2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op2ActionPerformed
        ShowTeachRec();
    }//GEN-LAST:event_op2ActionPerformed

    private void tnfil1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnfil1KeyReleased
        ShowTeachRec();
    }//GEN-LAST:event_tnfil1KeyReleased

    private void tnfil2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnfil2KeyReleased
        ShowTeachRec();
    }//GEN-LAST:event_tnfil2KeyReleased

    private void op3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op3ActionPerformed
        ShowTeachRec();
    }//GEN-LAST:event_op3ActionPerformed

    private void tdfilKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tdfilKeyReleased
        ShowTeachRec();
    }//GEN-LAST:event_tdfilKeyReleased

    private void op4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op4ActionPerformed
        ShowTeachRec();
    }//GEN-LAST:event_op4ActionPerformed

    private void tafil1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tafil1KeyReleased
        ShowTeachRec();
    }//GEN-LAST:event_tafil1KeyReleased

    private void tafil2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tafil2KeyReleased
        ShowTeachRec();
    }//GEN-LAST:event_tafil2KeyReleased

    private void op5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op5ActionPerformed
        ShowTeachRec();
    }//GEN-LAST:event_op5ActionPerformed

    private void tcnfilKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcnfilKeyReleased
        ShowTeachRec();
    }//GEN-LAST:event_tcnfilKeyReleased

    private void op6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op6ActionPerformed
        ShowTeachRec();
    }//GEN-LAST:event_op6ActionPerformed

    private void tsfilKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tsfilKeyReleased
        ShowTeachRec();
    }//GEN-LAST:event_tsfilKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ShowTeachRec();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeachersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeachersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeachersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeachersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeachersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable3;
    private javax.swing.JComboBox op1;
    private javax.swing.JComboBox op2;
    private javax.swing.JComboBox op3;
    private javax.swing.JComboBox op4;
    private javax.swing.JComboBox op5;
    private javax.swing.JComboBox op6;
    private javax.swing.JTextField tafil1;
    private javax.swing.JTextField tafil2;
    private javax.swing.JTextField tcnfil;
    private javax.swing.JTextField tdfil;
    private javax.swing.JTextField teachadd;
    private javax.swing.JTextField teachdept;
    private javax.swing.JTextField teachid;
    private javax.swing.JTextField teachname;
    private javax.swing.JTextField teachnum;
    private javax.swing.JTextField teachsts;
    private javax.swing.JTextField tidfil;
    private javax.swing.JTextField tnfil1;
    private javax.swing.JTextField tnfil2;
    private javax.swing.JTextField tsfil;
    // End of variables declaration//GEN-END:variables
}
